using System.Collections.Generic; // Provides List<T> for SackBlocks and MissingSequences collections

namespace Ucp // Root namespace for the UCP reliable-transport protocol library
{
    /// <summary>
    /// Common header fields present in every UCP packet. Includes type, flags,
    /// connection ID, and a microsecond-resolution timestamp. This header is
    /// the fixed-size prefix that all packet types share, enabling the transport
    /// layer to decode just enough to route the packet before fully parsing it.
    /// </summary>
    internal struct UcpCommonHeader // Fixed-size prefix common to every UCP packet; enables early routing without full parse
    {
        /// <summary>Packet type indicating how to interpret the remainder of the payload (Syn/Ack/Data/Fin/Rst).</summary>
        public UcpPacketType Type; // First byte of every packet; determines the packet subclass to instantiate

        /// <summary>Bitfield of flags modifying packet handling (need-ack, retransmit, fin-ack, has-ack-number).</summary>
        public UcpPacketFlags Flags; // Second byte of every packet; OR'd flag values controlling receiver behavior

        /// <summary>Identifies the logical connection this packet belongs to for demultiplexing.</summary>
        public uint ConnectionId; // Extracted by the transport layer to route the datagram to the correct connection

        /// <summary>Sender's monotonic timestamp in microseconds, used for RTT echo measurement when acknowledged.</summary>
        public long Timestamp; // Mirrored back by the peer in the EchoTimestamp field; enables per-packet RTT sampling
    }

    /// <summary>
    /// A Selective Acknowledgment block spanning a contiguous range of
    /// sequence numbers [Start, End] inclusive. Both bounds are part of
    /// the acknowledged data. These are generated by UcpSackGenerator
    /// and embedded in ACK or data packets to inform the sender which
    /// out-of-order ranges have been successfully received.
    /// </summary>
    internal struct SackBlock // Represents one contiguous acknowledged range in a SACK response
    {
        /// <summary>First sequence number in this acknowledged range (inclusive).</summary>
        public uint Start; // Lower bound of the contiguous received range

        /// <summary>Last sequence number in this acknowledged range (inclusive).</summary>
        public uint End; // Upper bound of the contiguous received range
    }

    /// <summary>
    /// Abstract base class for all UCP packet types. Every concrete packet
    /// (control, data, ack, nak, fec) derives from this and carries the
    /// common header. Enables polymorphic handling of diverse packet types
    /// through a single base-class reference.
    /// </summary>
    internal abstract class UcpPacket // Abstract base for polymorphic dispatch across all packet types
    {
        /// <summary>Common header fields shared by all packet types; always the first field decoded.</summary>
        public UcpCommonHeader Header; // Every packet starts with type, flags, connection ID, and timestamp
    }

    /// <summary>
    /// Represents a control packet: Syn, SynAck, Fin, or Rst.
    /// May optionally carry a sequence number for handshake packets.
    /// Carries cumulative acknowledgment when HasAckNumber flag is set
    /// in the header Flags field. Used for connection lifecycle management
    /// rather than data transfer.
    /// </summary>
    internal sealed class UcpControlPacket : UcpPacket // Connection-lifecycle packet for SYN, SYN-ACK, FIN, and RST operations
    {
        /// <summary>Whether a SequenceNumber is present in the encoded packet (only for Syn/SynAck with sequence).</summary>
        public bool HasSequenceNumber; // Controls whether the SequenceNumber field is serialized/deserialized

        /// <summary>Optional sequence number carried in Syn/SynAck packets to establish the initial sequence.</summary>
        public uint SequenceNumber; // The initial sequence sent during the three-way handshake

        /// <summary>Cumulative acknowledgment number carried on non-initial-SYN packets for piggybacked ACK support.</summary>
        public uint AckNumber; // Tells the peer that all data before this sequence has been received in order
    }

    /// <summary>
    /// Represents a data packet carrying a fragmented or whole application payload.
    /// Supports multi-fragment delivery through FragmentTotal and FragmentIndex
    /// for messages larger than the MSS. Carries piggybacked cumulative ACK,
    /// optional SACK blocks, flow-control window, and echo timestamp so a
    /// separate ACK packet is unnecessary during active data transfer, reducing
    /// protocol overhead on bidirectional flows.
    /// </summary>
    internal sealed class UcpDataPacket : UcpPacket // Application-data carrier with piggybacked ACK metadata to reduce round trips
    {
        /// <summary>Sequence number of this data segment, identifying its position in the byte stream.</summary>
        public uint SequenceNumber; // Assigned monotonically; receiver uses this to reorder and detect loss

        /// <summary>Total number of fragments in the logical message (1 = unfragmented, single-packet message).</summary>
        public ushort FragmentTotal; // Used by the receiver to know when all fragments of a message have arrived

        /// <summary>Zero-based index of this fragment within the logical message (0 = first fragment).</summary>
        public ushort FragmentIndex; // Enables the receiver to reassemble multi-packet messages in order

        /// <summary>The application payload bytes carried by this packet; may be up to MSS bytes.</summary>
        public byte[] Payload; // The actual user data to deliver upon reassembly

        /// <summary>Cumulative acknowledgment number piggybacked on this data packet; avoids sending a separate ACK.</summary>
        public uint AckNumber; // Informs the peer of received data without an extra control packet

        /// <summary>Selective acknowledgment blocks piggybacked on this data packet for out-of-order reception info.</summary>
        public List<SackBlock> SackBlocks = new List<SackBlock>(); // Enables fast retransmit without standalone ACK packets

        /// <summary>Advertised receive window size in bytes, piggybacked for flow control during data transfer.</summary>
        public uint WindowSize; // Tells the sender how much buffer space remains; prevents overwhelming the receiver

        /// <summary>Echoed timestamp from the last-received peer packet, for per-packet RTT measurement.</summary>
        public long EchoTimestamp; // Mirrored value from the peer's Header.Timestamp; delta gives the current RTT sample
    }

    /// <summary>
    /// Represents an acknowledgment packet with cumulative ACK number,
    /// optional SACK blocks, flow control window, and echo timestamp.
    /// Sent standalone when no data is flowing in the reverse direction,
    /// ensuring the sender always receives timely delivery confirmation.
    /// </summary>
    internal sealed class UcpAckPacket : UcpPacket // Standalone cumulative acknowledgment with optional SACK and flow-control metadata
    {
        /// <summary>Cumulative acknowledgment number: all sequences before this are received in order.</summary>
        public uint AckNumber; // Advances the sender's notion of delivered data; all bytes before this can be freed

        /// <summary>Selective acknowledgment blocks for out-of-order received ranges beyond the cumulative ACK.</summary>
        public List<SackBlock> SackBlocks = new List<SackBlock>(); // Informs sender of gaps so only missing packets are retransmitted

        /// <summary>Advertised receive window size in bytes for flow control enforcement.</summary>
        public uint WindowSize; // Receiver's remaining buffer capacity; sender must stay within this limit

        /// <summary>Echoed timestamp from the packet being acknowledged, enabling RTT sample computation.</summary>
        public long EchoTimestamp; // Delta between send time and this echo gives the measured round-trip time
    }

    /// <summary>
    /// Represents a negative acknowledgment packet listing missing sequence
    /// numbers that the receiver has detected as lost (typically via gap
    /// detection). Also carries the cumulative acknowledgment number so a
    /// separate ACK is not needed, reducing packet count during loss events.
    /// NAKs trigger immediate retransmission without waiting for the RTO timer,
    /// dramatically improving loss recovery latency.
    /// </summary>
    internal sealed class UcpNakPacket : UcpPacket // Explicit loss-report packet listing specific missing sequences for fast retransmit
    {
        /// <summary>Cumulative acknowledgment number; all data before this sequence is acknowledged as delivered.</summary>
        public uint AckNumber; // Confirms delivery up to this sequence even while reporting later losses

        /// <summary>List of sequence numbers reported as missing by the receiver, triggering fast retransmission.</summary>
        public List<uint> MissingSequences = new List<uint>(); // Each entry is a specific packet the receiver has not yet received
    }

    /// <summary>
    /// Represents a Forward Error Correction repair packet carrying XOR-based parity
    /// data for a specific group of data packets. Each repair packet encodes the XOR
    /// of all payloads in its group, allowing the receiver to reconstruct any single
    /// lost packet within the group without requiring a retransmission. This is
    /// especially valuable in high-latency or high-loss environments where round-trip
    /// time makes retransmission costly.
    /// </summary>
    internal sealed class UcpFecRepairPacket : UcpPacket // XOR-parity recovery packet enabling single-packet loss repair without retransmission
    {
        /// <summary>Base sequence number identifying the FEC group this repair packet belongs to.</summary>
        public uint GroupId; // All data packets in a group share a common group identifier for XOR parity computation

        /// <summary>Index of this repair within the group (0-based); typically 0 for single-repair groups.</summary>
        public byte GroupIndex; // Supports multiple repair packets per group for higher loss tolerance

        /// <summary>Parity repair payload computed as XOR of all data packet payloads in the group.</summary>
        public byte[] Payload; // XOR-sum of group payloads; any single lost packet can be recovered from this and the other group members
    }
}
